### PR TITLE
Add toggle for publishing

### PR DESCRIPTION
**Pull request by nuest**
This is the first part of #23

### CODE REVIEW

**Comment by nuest** [comment]
I had to add considerable timeouts to the post requests, maybe the new sandbox has some throttling issues? I also got a few 504 Gateway Timeout errors on the "publish" action, but the record is published just fine in the sandbox, see https://sandbox.zenodo.org/records/10001337

**Comment by cthoyt** [comment]
@nuest maybe you're aware, but Zenodo just did a full backend upgrade last week. It might be the case that the zenodo-client doesn't work at all anymore, I haven't had time to look and see to what extent the API changed

**Comment by nuest** [comment]
I was aware, but I rather attributed this to performance issues with the sandbox.

Let me check if I can see what changed for the `publish` action!

**Comment by nuest** [comment]
It seems like the client hast do create a draft first, and that the action URL for publishing then also changes:

https://inveniordm.docs.cern.ch/reference/rest_api_drafts_records/#edit-a-published-record-create-a-draft-record-from-a-published-record

**Comment by nuest** [comment]
@cthoyt https://developers.zenodo.org/ is back up, so that's at least a chance to take a look at the changes. It's hard for me to commit a specific amount of time, but it would be really useful to get the lib working again, so let me know if you need help, e.g., with testing.

**Comment by nuest** [comment]
@cthoyt Hi! :wave: Did you give the API updates a look? Shall I rebase my changes, or can I do some testing?

**Comment by cthoyt** [comment]
@nuest thanks, I updated with the new API in 0468a69ba773b8ac8d93d504711df2eff26cb2d0 and updated your branch. I also moved some of the new docs out of the README and into the more detailed docs, to de-clutter the front page. It appears there's still some issues with you missing a zenodo API token in your github secrets. I will try and improve the error message to make this more obvious, but the short version is you need to have this


Screenshot 2023-12-11 at 15 27 26

when you navigate to https://github.com/nuest/zenodo-client/settings/secrets/actions

**Comment by cthoyt** [comment]
Superseded by #36

**Pull request closed without merging**
